name: Update metadata

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const {readFileSync} = require('node:fs')

          const package = JSON.parse(readFileSync('./package.json'))

          const {owner, repo} = context.repo
          const {description, homepage, keywords} = package

          octokit.rest.repos.update({
            owner,
            repo,
            description,
            homepage,
          });

          octokit.rest.repos.replaceAllTopics({
            owner,
            repo,
            names: keywords
          });

